config/routes.rb
require 'sidekiq/web'

BP1Parserhtml::Application.routes.draw do

  resources :articles

  root  'articles#index'
  match '/zberac', to: 'pages#home', via:'get'
  match '/run', to: 'pages#run', via:'get'
  match '/help', to: 'pages#help', via: 'get'

  match '/search', to: 'articles#search', via:'get'
  match '/update', to: 'articles#update', via:'get'

  mount Sidekiq::Web, at: '/sidekiq'

  

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :user

end

app/models/evaluation.rb
class Evaluation < ActiveRecord::Base

  def save_click(doc_id)
    evaluator = Evaluation.find(1)

    if doc_id == -1
      evaluator.update :no_person => evaluator.no_person+1
    else
      evaluator.update :person => evaluator.person+1
    end
  end
end

app/models/similarities.rb
class Similarities < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :documents

  def create_user(id)
    unless User.exists?(id)
      User.create(:name => "User", :surname => id, :id => id, :avg_rating => 0)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include ArticlesHelper
  before_action only: [:show, :search]

  def index
  end

  def search
    @search_adjust = SearchArticle.new
    #ulozenie id pouzivatela
    session[:current_user] = params[:userid]
    user = User.new
    #vytvorenie noveho pouzivatela, ak este neexistuje
    user.create_user(params[:userid])

    if params[:q].present?
      #vyhladanie dokumentov
      @result = @search_adjust.search_articles(params[:q], (Elasticsearch::Client.new log: true))
      @result = Hashie::Mash.new @result
      #ohodnotenie dokumentov
      result_brefore_paging = @search_adjust.weighted_sum(params[:userid], @result)
      #vytvorenie zoznamu na evaluaciu
      covering = @search_adjust.evaluation(result_brefore_paging, @result)
      #strankovanie
      @articles = Kaminari.paginate_array(covering).page(params[:page]).per(10)

      render :action => "search"
    else
      render :action => "index"
    end
  end

  def update
    @search_adjust = SearchArticle.new
    evaluator = Evaluation.new
    #ulozenie kliknutia na evaluaciu do databazy
    suffix_id = params[:doc_id][13..params[:doc_id].length-1].to_i
    puts "[Info]: suffix of doc_id: #{suffix_id}"
    evaluator.save_click(suffix_id)

    if  suffix_id  != -1
      doc_id = params[:doc_id][5..11].to_i

      @user = User.find(session[:current_user])

      test = Document.find_by_sql("select user_id from documents where document = #{doc_id} and user_id = #{session[:current_user]}")

      if test.present?
        @user.documents.increment_counter :doc_rating, Document.select(:id).where(:document => doc_id)
        @user.update(:avg_rating=>@user.documents.where(:user_id => session[:current_user]).average(:doc_rating))
      else
        @user.documents.create(:document=>doc_id, :doc_rating=>1)
        @user.update(:avg_rating=>@user.documents.where(:user_id => session[:current_user]).average(:doc_rating))
      end

      #vyratanie podobnosti
      @search_adjust.compute_similarities(Document.select(:document).distinct, doc_id)

    end
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
  end

  def destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :publisher, :conference, :date, :authors, :abstract, :tags, :classifications, :published_in)
    end

end

app/controllers/pages_controller.rb
require 'rubygems'
require 'nokogiri'
require 'open-uri'
require 'tire'

class PagesController < ApplicationController
  def home
  end

  def help
   Tire.index 'articles' do
      delete
      create
      refresh
    end

  end

  def run
    if params[:min].empty? or params[:max].empty?
      redirect_to :back
    end

    id = params[:min].to_i
    max = params[:max].to_i

    while id < max do
      HardWorker.perform_async(id)
      puts "Next id in 5 seconds".red
      sleep 5
      id += 1
    end

    Tire.index 'articles' do
      refresh
    end
   end
  end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title)
    base_title = ""

    if page_title.empty?
      return base_title
    else
      return "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper

  def check_presence(value)
    if value.present?
      value
    end
  end

  def shorten_abstract(text)
    if text.length > 400
      shorten = String.new

      (0..400).each { |i|
        shorten[i] = text[i]
      }
      shorten << "..."
    else
      return text
    end


    return shorten
  end



end

app/helpers/pages_helper.rb
module PagesHelper

end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :publisher %><br>
    <%= f.text_field :publisher %>
  </div>
  <div class="field">
    <%= f.label :conference %><br>
    <%= f.text_field :conference %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :authors %><br>
    <%= f.text_field :authors %>
  </div>
  <div class="field">
    <%= f.label :abstract %><br>
    <%= f.text_field :abstract %>
  </div>
  <div class="field">
    <%= f.label :tags %><br>
    <%= f.text_field :tags %>
  </div>
  <div class="field">
    <%= f.label :classifications %><br>
    <%= f.text_field :classifications %>
  </div>
  <div class="field">
    <%= f.label :published_in %><br>
    <%= f.text_field :published_in %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div class="center hero-unit">
<h3>Personalizované vyhľadávanie v digitálnej knižnici</h3> <br />
<%= form_tag search_path, :method => 'get' do %>
    <%= text_field_tag :q, params[:q], placeholder: "Enter search query...", class: 'text_field_class' %>
    <br />
    <%= number_field_tag :userid, params[:userid], placeholder: "Enter user id...", required: true  %>
    <br />
    <%= submit_tag("Search", class: "btn btn-small btn-primary") %>
<% end %>

</div>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/search.html.erb
<script>
    $("[id^=text_]").hide();

    $("button").click(function (event) {
        if ($(this).text().trim() == 'Show more') {
            $("#text_" + event.target.id).fadeToggle(600);
            $("#short_" + event.target.id).fadeToggle(0);
            $(this).text("Show less")
        } else {
            $("#text_" + event.target.id).fadeToggle(0);
            $("#short_" + event.target.id).fadeToggle(600);
            $(this).text("Show more")
        }
    });

    $("[id^=link_]").click(function (event) {
        $.ajax({
            url: '/update',
            success: function (data) {
            },
            data: {doc_id: event.target.id}
        });
    });
</script>

<header>
  <br />
  <strong><%= link_to 'Back', articles_path if params[:q] %></strong>
</header>

<article>
<div class="article">
  <div class="result">
    <p><b>Displaying results for search query:</b> <strong><%= params[:q] %></strong></p>
    <br />
    <div>Took: <%= @result.took %>ms, total number of results: <%= @result.hits.total %></div>
  </div>

  <% if @articles.present? %>
      <% @articles.each do |article| %>
          <div class="data">
            <strong><%= link_to article[0]._source.citation_title, "http://dl.acm.org/citation.cfm?id=#{article[0]._source.id}", :id => "link_#{article[0]._source.id}_#{article[1]}" %></strong>
            <p>
              <small><%= check_presence(article[0]._source.tags) %></small>
            </p>
            <p>
              <small><%= check_presence(article[0]._source.citation_date) %></small>
            </p>
            <% if article[0]._source.authors.present? %>
                <% for i in 0..article[0]._source.authors.length-1 %>
                    <p>
                      <strong>
                        <small><%= link_to article[0]._source.authors[i].name, article[0]._source.authors[i].page %></small>
                      </strong>
                      <small><%= article[0]._source.authors[i].institution %></small>
                    </p>
                <% end %>
            <% end %>

            <div id="abstract">
              <%= content_tag :p, id: "short_#{article[0]._source.id}_#{article[1]}" do -%>
                  <%= shorten_abstract(article[0]._source.abstract[0].text) %>
              <% end -%>

              <%= content_tag :p, id: "text_#{article[0]._source.id}_#{article[1]}" do -%>
                  <%= article[0]._source.abstract[0].text %>
              <% end -%>

              <%= content_tag :button, id: "#{article[0]._source.id}_#{article[1]}" do -%>
                  Show more
              <% end -%>
            </div>
          </div>
      <% end %>
  <% end %>
  <br/>
</div>
<%begin %>
  <%= paginate @articles %>
<% rescue%>
  <%= puts "[Rescued]: Pagination known, but unresolved problem" %>
 <%end %>
</article>
<footer>
  <hr>
  <p>
  Copyright (c) 2014 Bakalársky projekt @ Matej Čaja @ <a href="http://www.fiit.stuba.sk/">FIIT</a>
  </p>
</footer>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.citation_title %>
</p>

<p>
  <strong>Publisher:</strong>
  <%= @article.citation_publisher %>
</p>

<p>
  <strong>Conference:</strong>
  <%= @article.citation_conference %>
</p>

<p>
  <strong>Date:</strong>
  <%= @article.citation_date %>
</p>

<p>
  <strong>Authors:</strong>
  <%= @article.authors %>
</p>

<p>
  <strong>Abstract:</strong>
  <%= @article.abstract %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @article.tags %>
</p>

<p>
  <strong>Classifications:</strong>
  <%= @article.classifications %>
</p>

<p>
  <strong>Published in:</strong>
  <%= @article.published_in %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/articles/update.html.erb
<p>redirected</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "custom", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/help.html.erb
<div class="center hero-unit">

  <h2>BP1 HTML parser</h2>
<h2>ElasticSearch has been cleared !</h2>

<%= link_to "HOME", root_path %>

</div>

app/views/pages/home.html.erb
<div class="center hero-unit">
  <h3>Zberač údajov</h3>

  <div class="form" id="form">
    <%= form_tag(run_path, method: "get") do %>

      <%= label_tag(:min, "Min") %>
      <%= text_field_tag(:min) %>

      <%= label_tag(:max, "Max") %>
      <%= text_field_tag(:max) %>
      <br />

      <%= submit_tag("Run in background", class: "btn btn-small btn-primary") %>

  <% end %>
    <br />
    <%= link_to "Back to search", articles_path %>
  </div>
</div>

app/views/pages/run.html.erb
<div class="center hero-unit">
    <h2>Done</h2>
  <%= link_to "Head back!", zberac_path %>
</div>